### ISSUE TITLE
Code-Reviews should be Contribution-Reviews

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/scorecard#1018]
**Describe the bug**
`Code-Reviews` implies that only code contributions need review. In *practice*, settings to enforce reviews enforce them for *any* contribution, not just code, and I think that's the way it should be anyway.

So `Code-Reviews` should be renamed to `Contribution-Reviews` (or similar) everywhere.

**Comment by laurentsimon** [comment]
Thanks David. Note that GitHub settings are unfortunately *not* all defined via `config-as-code`.: e.g., branch protection, 2FA, GitHub action settings, etc. I would love to see this change too.

**Comment by laurentsimon** [comment]
For this issue:
1. Update this file https://github.com/ossf/scorecard/blob/main/docs/checks/internal/checks.yaml
2. run `make generate-docs`
3. Update the name of the check in https://github.com/ossf/scorecard/blob/main/checks/code_review.go#L26
4. Update the file name to contribution_review.go

**Comment by neil465** [comment]
I would like to work on this issue.

**Comment by inferno-chromium** [comment]
Code-Review is a common and easy to understand term. Contribution-Reviews is very confusing, i don't think it helps clarify the purpose you are trying to solve. if settings change go in code, it will be still governed by code review. and if someone changes settings outside of it, like in admin console, then first game is already over, and also, we don't have great ways to enforce review of it. if we get to a point of monitoring those settings, it will be better to be its own check, rather than changing the name of code review check.

**Comment by neil465** [comment]
> Code-Review is a common and easy to understand term. Contribution-Reviews is very confusing, i don't think it helps clarify the purpose you are trying to solve. if settings change go in code, it will be still governed by code review. and if someone changes settings outside of it, like in admin console, then first game is already over, and also, we don't have great ways to enforce review of it. if we get to a point of monitoring those settings, it will be better to be its own check, rather than changing the name of code review check.

Ok, thanks

**Comment by laurentsimon** [comment]
Closing the bug then. Please re-open if needed.
