### ISSUE TITLE
Feature: improve GitHub URL validation

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#1149]
GitHub usernames need to follow the below rules:

1. Only alphanumeric characters (a-z, A-Z, 0-9) and single hyphens (no consecutive hyphens) allowed.
2. Cannot start or end with hyphens.
3. Max character length is 39.

We can use these rules to improve how we [validate GitHub URLs](https://github.com/ossf/scorecard/blob/96140f9646f62e444f1d0630dd3f4a65bcfc5c8d/repos/repo_url.go#L97).

**Comment by r0mdau** [comment]
I have something working here : https://github.com/r0mdau/scorecard/commit/b70b34426cd18146449e33b0e3f423e26c2e1f31

We have a decision to make regarding `cron/data/projects.csv` file because the Makefile target `add-projects` fails for each repository url where the username is not good.

Should I remove all repositories url that do not match ?
