### ISSUE TITLE
Inconsistency in Organisations

### ISSUE THREAD

**Issue by ShubhamPalriwala** [ossf/scorecard#1179]
**Describe the bug**
I recently ran a Scorecard Scan via Docker on [kyverno/kyverno](https://github.com/kyverno/kyverno), and in the Contributors section, the organisations that are mentioned, some are prepended with an `@` while some aren't!
Proof:
![image](https://user-images.githubusercontent.com/55556994/139253252-f9a24782-59f0-4780-a214-50e7952b6b59.png)
As you can see only Prometheus is tagged here while the others aren't! This creates an incosistency.

**Reproduction steps**
1. Scan kyverno/kyverno with the Docker installation

**Expected behavior**
Either all the organisations should be or none shouldn't. In my opinion, all the organisations should be tagged.

**Comment by azeemshaikh38** [comment]
Looks like one the company names is specified as "@litmuschaos @prometheus". We only trim the `@` from the [beginning of company name](https://github.com/ossf/scorecard/blob/main/checks/contributors.go#L63), hence the inconsistency in this case. I'm closing this since this is working as expected IMO. However, happy to review a PR which tackles the `@` handling better than what we currently have.
