### ISSUE TITLE
Feature: relaxing npm pin validation to versions rather than hashes

### ISSUE THREAD

**Issue by godofredoc** [ossf/scorecard#1754]
**Is your feature request related to a problem? Please describe.**
The only way to pin npm dependencies by hash is using the github repo. Installation of complex dependencies like `npm install -g firebase/firebase-tools#23dc81fd065f4cfaa172cff535cafdd9a8c11c23` require the manual installation of multiple other packages and tools making either infeasible or difficult to maintain.

**Describe the solution you'd like**
Pinning by version not raising security alerts for npm dependencies until npm supports pinning by hash.

**Describe alternatives you've considered**
The alternative described in the [firebase page](https://firebase.google.com/docs/cli#mac-linux-auto-script) is to curl a script to a bash terminal which seems worse than pinning by version. 

**Additional context**

**Comment by laurentsimon** [comment]
Thanks for the issue. I agree the doc is spare how to achieve hash pinning. (we have a best security npm practice doc on the way with OSSF).

**Some context**: npm versions are immutable _but_ it's enforced by npm registry, not the manifest. Since it's not too difficult to have hash pinning and the tooling exists, it's feasible to get the npm registry our of the TCB.

**Installation**
Using `npm install/i` allows to pin, but:
1. Dependabot/renovatebot tools don't parse scripts and workflows, so you'd never receive updates if you do that

** Manifest **
The answer is to use a manifest for everything, this way you will receive updates. Firebase is a set of CLI tools, so you need to create a "wrapper" manifest:
```
{
  "name": "wrapper-firebase-tools-cli",
  "version": "1.0.0", // whichever version you want
  "dependencies": {
    "firebase/firebase-tools": "v10.2.2"
  }
}
```

Locally, on your dev machine, run `npm install --package-lock-only` to create the lock file. Then commit both the manifest and lock files to GitHub, maybe under `.github/workflows/dependencies/firebase/`

In your GitHub workflows, do:
```
cp .github/workflows/dependencies/firebase/* .
npm ci # this command uses the hashes in the lock file
```

Let me know if this help or not. If you end up needing to tweak this procedure, please post your final solution here so we can update the best practice doc we're about t publish.

Thanks!

**Comment by godofredoc** [comment]
Thank you for the explanation the only additional thing that I needed to add is the local modules .bin folder to the path where we are expecting to run the binaries from the `npm ci` installation. 

```
env:
          PATH: 'node_modules/.bin/'
```

**Comment by laurentsimon** [comment]
Great, can you link to the PR? I'll add this to the npm best practice doc for additional details.
So `npm ci` does not understand the `-g` flag, that's why you need to set this extra `PATH`?

**Comment by godofredoc** [comment]
That is correct, the version of npm I experimented with didn't support the -g flag and I had to extend `PATH` to be able to execute the firebase binary without the full path.

This is the PR https://github.com/flutter/website/pull/6957/. I'll report back once it has been fully validated.

**Comment by laurentsimon** [comment]
Brilliant, thanks! BTW, I think your PR lacks the wrapper's manifest and lock files

**Comment by godofredoc** [comment]
Turns out the files were already there but not being used:

* https://github.com/flutter/website/blob/main/package.json
* https://github.com/flutter/website/blob/main/package-lock.json

**Comment by laurentsimon** [comment]
Closing this bug. Thanks @[godofredoc](https://github.com/godofredoc) for the report. Feel free to re-open if you think it needs further input from us. Thanks!

**Comment by godofredoc** [comment]
@laurentsimon an update on updating the PATH to include `npm ci` dependencies. It took me some trial and error to find that  `$HOME/node_modules/.bin/` was not correct.

These are the configs that finally worked for my use case:
```
- name: Update path
        run: echo "./node_modules/.bin/" >> $GITHUB_PATH
```
Example: https://github.com/flutter/website/pull/6999

**Comment by laurentsimon** [comment]
Thank you, and sorry for the inconvenience. I'm going t add this to the Npm best practice doc
