### ISSUE TITLE
Scanning feature branches

### ISSUE THREAD

**Issue by ragav24** [ossf/scorecard#1799]
**Is your feature request related to a problem? Please describe.**
When i run the scan using cli scorecard --repo=github.com/ossf-tests/scorecard-check-branch-protection-e2e, by default it scans the default branch.

Would like to run it in different branch for same repo.

**Describe the solution you'd like**
Add --branch=newBranch to run it any branch

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by azeemshaikh38** [comment]
We do not plan to support scanning feature branches since many GitHub APIs we rely on, only work for the default branch.

If you want to run Scorecard on a non-default branch, the recommendation is to check out the feature branch locally and run:

```
scorecard --local=<path_to_repo>
```

We are working on further improving this support in #1709.
