### ISSUE TITLE
Release 4.4.0 does not offer tarballs for all platforms

### ISSUE THREAD

**Issue by nicholasdille** [ossf/scorecard#2024]
**Describe the bug**
Release 4.4.0 does not offer tarballs for all platforms. Instead for amd64, a binary is attached. This change makes it difficult to process updates automatically

**Reproduction steps**
1. Check assets of release 4.4.0
2. COmpare to assets of previous releases, e.g. 4.3.1

**Expected behavior**
Release 4.4.0 offers tarballs for all supported platforms

**Additional context**
The project [docker-setup](https://github.com/nicholasdille/docker-setup) relies on automated updates using RenovateBot. Since release 4.4.0, the installation of scorecard fails because the amd64 tarball is missing.

**Comment by laurentsimon** [comment]
You're correct, it's because I disabled Goreleaser for the amd64 build

**Comment by azeemshaikh38** [comment]
Thanks for the report @nicholasdille. @laurentsimon definitely need to fix before we rollout the SLSA workflow. Assigning to you.

**Comment by naveensrinivasan** [comment]
> Thanks for the report @nicholasdille. @laurentsimon definitely need to fix before we rollout the SLSA workflow. Assigning to you.

This should be a bug in SLSA Workflow.

**Comment by laurentsimon** [comment]
The fix I propose is to rename the final binary to something different. When we decide to fully migrate to the SSLSA builders, we'll rename them.

@nicholasdille Can you confirm that using binaries instead of tarballs/zip works? I think your problem is that it was inconsistent, so you script expected to have tarballs, or binaries, but not both. (Not all projects use tarballs so I think this would work in your case)

**Comment by nicholasdille** [comment]
Thanks for the update. Rolling out an SLSA workflow sound terrific :-) Verifying the SLSA provenance is already on my list. Unfortunately, very few projects have started to implement this.

@laurentsimon Binaries as well as tarballs are fine. I can even manage if they are mixed for different platforms. But consistency across releases would be awesome :-)

**Comment by laurentsimon** [comment]
I will fix the current release by adding the tarball.

@azeemshaikh38 @naveensrinivasan is there a reasons we're using compressed assets in our release? Does GH have limitation on sizes. Otherwise a simple solution would be to change the GoReleaser config to output binaries instead of zipped tarballs. (tarballs are useful if we output multiple binaries per OS/Arch, but we don't need it)

@nicholasdille if you get some of the project you fetch binaries from to adopt some SLSA builders, check out sos.dev: it lets you be rewarded for improving supply-chain security.

Also, we're going to release https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/generic this month, and it should be easy for most projects to integrate.. maybe a path to get projects to adapt SLSA and use sos.dev :)

**Comment by laurentsimon** [comment]
fyi, I've fixed the existing release by uploading a tarball.

I'll wait to see what @naveensrinivasan and @azeemshaikh38 think w.r.t using binaries in the GoReleaser config

**Comment by laurentsimon** [comment]
> > is there a reasons we're using compressed assets in our release?
> 
> Don't think there is a strong reason. However, if we simply shift over to using binaries instead of tarballs I wonder how many other users we might break. Something to consider for your SLSA workflow - it might be important to provide users of the workflow the option to output binaries or tarballs.

yep that's something we'd like to support at some point for the Go builder, we have not prioritized it. I think we need to support multiple builds first. In the meantime, the generic generator will sidestep this problem by letting users add provenance to whatever they want.

> On a side note, maybe it's a good thing we use tarballs? That way, every tarball can contain related metadata for the binary (SLSA provenance, signature etc.) along with the binary. Again, not a strong reason to use tarballs, just seems neat :)

Agreed. Actually I was wondering whether the provenance should be on the full zip / tarball file, or inside.. or both

**Comment by spencerschrock** [comment]
> fyi, I've fixed the existing release by uploading a tarball.

is the tarball correct? `scorecard_4.4.0_linux_amd64.tar.gz` is only
32.9 KB. I don't think the executable is included, just a `scorecard-linux-amd64.intoto.jsonl` file

**Comment by azeemshaikh38** [comment]
> Actually I was wondering whether the provenance should be on the full zip / tarball file, or inside.. or both

Good point, might be something to discuss with the SLSA folks. IIUC, if the compression step from zip can be part of the provenance, then just a single provenance outside the tarball should be enough.

**Comment by laurentsimon** [comment]
We may generate binaries instead of zip in the future. If we do that it will break your setup. Since we're still experimenting with SLSA, I wanted to. give you a notice.

**Comment by nicholasdille** [comment]
Thanks for the heads up. Scorecard is treated like a dependency. Any update is automatically tested. If it fails to install I can take a look. So any changes to the release assets will show up so I can fix the installation for a new version. So... No worries 😀
