### ISSUE TITLE
Capitalize proper nouns like Dependabot, Renovate, and GitHub

### ISSUE THREAD

**Issue by HonkingGoose** [ossf/scorecard#2055]
Proper nouns should be capitalized properly.

Suggested replacements on `*.md` files:

- `dependabot` -> `Dependabot`
- `renovatebot` -> `Renovate` or `Renovate bot`
- ` github ` -> ` GitHub `

**Comment by naveensrinivasan** [comment]
Thank you! Would you like to do a PR?

**Comment by HonkingGoose** [comment]
I'll let you guys do it. 😉

**Comment by singhsaurabh** [comment]
In `./docs/checks.md` following lines need update
====
in line number 206
- determines whether the most recent (~30) commits have a _Github_-approved review

in line number 263
- logging _github_ context and secrets, or use of potentially untrusted inputs in scripts.

in line number 279
- can add their own content to certain _github_ context variables that are considered 

in line number 294  
- specifically [_dependabot_](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates) or

in line number 295 
- [_renovatebot_](https://docs.renovatebot.com/configuration-options/). Out-of-date

in line number 312 

- Signup for automatic dependency updates with [_dependabot_](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dep    endency-updates) or [_renovatebot_](https://docs.renovatebot.com/configuration-options/) and place the config file in the locations that are recommended by these tools. Due to https://github.com/dependa    bot/dependabot-core/issues/2804 Dependabot can be enabled for forks where security updates have ever been turned on so projects maintaining stable forks should evaluate whether this behavior is satisfactory before turning it on.

in line number 313 
- Unlike _dependabot_, _renovatebot_ has support to migrate dockerfiles' dependencies from version pinning to hash pinning  via the [pinDigests setting](https://docs.renovatebot.com/configuration-options/    #pindigests) without aditional manual effort.

in line number 475
- _Github's_ [_dependabot_](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)

in line number 476 
- or [_renovate bot_](https://github.com/renovatebot/renovate).

in line number 491
- The checks currently looks for known _Github_ apps such as

**Comment by singhsaurabh** [comment]
@naveensrinivasan can I take this issue and make the changes and create PR?
Thank You

**Comment by singhsaurabh** [comment]
@naveensrinivasan Please review [PR-2061](https://github.com/ossf/scorecard/pull/2061/). I resolved the conflicts but current PR has my older changes also which are made with respect to the [issue-1534](https://github.com/ossf/scorecard/issues/1534). Looks like something I didn’t do correctly while committing new changes. 
Please help.
Thank You

**Comment by singhsaurabh** [comment]
Updated the changes in `checks.yaml` file and build the doc. 

<img width="1034" alt="Screenshot 2022-07-25 at 23 18 28" src="https://user-images.githubusercontent.com/6647276/180885573-c29511c7-e7f3-47e1-9e29-e9712d15326d.png">

Please review the PR https://github.com/ossf/scorecard/pull/2061
Thank You
