### ISSUE TITLE
Feature - Implement monitoring of the cron job. 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#247]
**Is your feature request related to a problem? Please describe.**
The scorecard cron runs twice a week. Need to implement monitoring of this cron job for success and failures. 

**Describe the solution you'd like**
An alert when the job isn't running and producing the necessary output.

**Comment by azeemshaikh38** [comment]
Assigning to myself. Already added monitoring for some metrics like latency, outgoing requests etc. Also, the framework to add more metric is already in place.

Keeping this open until we setup email/Slack alerts for cron job failures.

**Comment by azeemshaikh38** [comment]
I've setup alerting for PubSub when there are: (i) repeated worker restarts and (ii) CheckRuntime 95th percentile latencies are higher than 10min.

![image](https://user-images.githubusercontent.com/4825078/121579050-312fb700-c9e0-11eb-995a-b5ba7e51cf40.png)


Stackdriver monitoring for CheckRuntime, RepoRuntime and OutgoingHTTPRequests are also in place and working fine so far.

Closing this issue since we have basic monitoring/alerting setup. Can add more as needed.
