### ISSUE TITLE
Most recent release's assets do not include SLSA provenance attestation

### ISSUE THREAD

**Issue by joshuagl** [ossf/scorecard#2515]
**Describe the bug**
I'm trying to follow the [Verifying SLSA provenance for downloaded releases](https://github.com/ossf/scorecard/blob/c3f4e31c28c22c4daefe510385fcc97f4faa816e/README.md#verifying-slsa-provenance-for-downloaded-releases) steps in the README but:

**Reproduction steps**
1. The latest (4.8.0) release does not include an attestation.intoto.jsonl file in its assets (4.7.0 does, however).
2. The GitHub releases link in that section of the README links to the releases for jib

**Expected behavior**
- attestations are published for all new releases
- documentation points to scorecard releases

**Comment by naveensrinivasan** [comment]
@laurentsimon 👀

**Comment by laurentsimon** [comment]
This is due to the Sigstore breaking changes that were made during the recent Sigstore GA. All existing tools broke, and I think scorecard got caught as well. The next release should work and we should update to the latest version. Let me send a PR to update it - I'm not sure why dependabot is not sending PRs for ... @naveensrinivasan have you seen any?

**Comment by laurentsimon** [comment]
They do now https://github.com/ossf/scorecard/releases/tag/v4.10.0
