### ISSUE TITLE
Feature: Token-Permissions should ignore `on: pull_request` workflows

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard#2850]
**Is your feature request related to a problem? Please describe.**
The Token-Permissions check penalizes workflows that only run `on: pull_request` even though such workflows always run with read-only tokens.

**Describe the solution you'd like**
Workflows that only run `on: pull_request` should be ignored (or not penalized) by the Token-Permissions check.

**Describe alternatives you've considered**
We could also create a very light penalty for such workflows (due to the risk of modifying the workflow to run on other triggers in the future). However, my understanding of the Token-Permissions logic makes me think this would require a greater intervention for (imo) little benefit.

**Comment by pnacht** [comment]
Ah, of course, forgot about that.

But... what can a malicious maintainer (user that can create local branches) do using an `on: PR` workflow that they can't do themselves?

**Comment by varunsh-coder** [comment]
The threat isn't just from a malicious maintainer. It can also be from a harmful or hacked dependency.

Imagine you create a local branch and add a new dependency that turns out to be malicious. When the pull request workflow runs, this malicious dependency could use the GITHUB_TOKEN and tamper the releases, packages, etc. Right?

**Comment by diogoteles08** [comment]
Are we good to close this?
