### ISSUE TITLE
Feature: enable only the probes for the checks run

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#3049]
We currently run all probes in the non-released probe support. We need to be able to select the probes foe the checks being run.

**Comment by laurentsimon** [comment]
don't close

**Comment by spencerschrock** [comment]
Specifically, this has to do with this part of the code:
https://github.com/ossf/scorecard/blob/55b6b7686d64d0f87b96c2f53742df1ae109b570/pkg/scorecard.go#L170-L185

We currently produce the findings in each check, but don't directly add them to the results. Since the checks operate concurrently, we probably need to use channels like we do with the individual check results.
