### ISSUE TITLE
Difference between GitLab refs and GitHub refs

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#3395]
As part of #3394 , I noticed the GitLab handler assumes `ref` refers to a SHA. But in the GitLab API [link](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines), ref is assumed to be 
> The branch or tag to check for the latest pipeline. Defaults to the default branch when not specified.

Where as on GitHub [doc link](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#list-check-runs-for-a-git-reference) refs can be commits, or branches, or tags:
> The commit reference. Can be a commit SHA, branch name (heads/BRANCH_NAME), or tag name (tags/TAG_NAME).

We may need to fix the GitLab code to distinguish between branches, tags, and commits.

**Comment by ashearin** [comment]
I'm not sure if this is an issue, at least for the SAST and CI-tests checks in Gitlab. The function that pulls in the commits (`ListCommits`) can handle a branch/tag/sha/shortsha. the function used [list-repository-commits](https://docs.gitlab.com/ee/api/commits.html#list-repository-commits) uses `ref_name` which is described as: 
```
ref_name: The name of a repository branch, tag or revision range, or if not given the default branch
``` 
I tested my local build with tag/branch/sha and each returned the proper content. (FWIW)

Once the list of commits is returned we are able to use the commit shas to pull appropriate pipeline results in `CheckRunsFrom(HEADsha)`. The call to [ListProjectPipeline](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines) can take either sha or ref, but since we already have the commit history based off the branch/tag/sha I dont think it makes sense to use the branch name for this call. 

SAST and CI_tests both start with calls to `ListCommits` and `CheckRunsFrom` but deviate after, I'll discuss differences below:

- CI-Tests:
   - Last step here before evaluation is `ListStatuses(HEADsha)` the gitlab API call here is [`GetCommitStatuses`](https://docs.gitlab.com/ee/api/commits.html#list-the-statuses-of-a-commit) and requires a sha (can optionally take a ref also but seems unnecessary)
- SAST: 
  - Next `codeQLInCheckDefinitions` is called and looks like it only handles github actions? 
  - FInal step before evaluation is `getSonarWorkflows` with no calls to gitlab or use of the ref. 
  - Once this check is modified to work with Gitlab it _might_ need to keep sha/ref straight, but from what I can see we'd just process the commits pulled in `ListCommits` with another api call to get what we need.
  
  LMK if I'm off base or missing something. Happy to contribute this fix if needed.

**Comment by spencerschrock** [comment]
> * LMK if I'm off base or missing something. Happy to contribute this fix if needed.

It's been a bit since this issue, so my memory is slightly fuzzy. The issue may have been a naming/argument assumption problem, where the function is called `listCheckRunsForRef`, but the code always assumes the arg is a SHA

https://github.com/ossf/scorecard/blob/5dc03b72e109d67afe4c91a0fbe52a3c1678a97f/clients/gitlabrepo/checkruns.go#L34-L39

The code assumes ref is a SHA because it has the following line:
```go
SHA:         &ref, 
```

So if we ever called listCheckRunsForRef("somebranch") I think the result would be incorrect. The code always calls it with a SHA though, so there's no bug yet. The solution would be figuring out if ref is a commit or something else, and setting Ref or SHA accordingly.
