### ISSUE TITLE
Missing checks in API response

### ISSUE THREAD

**Issue by UlisesGascon** [ossf/scorecard#3438]
**Describe the bug**

While comparing the scoring with the API:
- Request1: [Nodejs (bd31d489615b424202553ffe1a5093a19d5e5e1f)](https://api.securityscorecards.dev/projects/github.com/nodejs/nodejs.org/?commit=bd31d489615b424202553ffe1a5093a19d5e5e1f)
- Request2: [Nodejs (1fbd908497ece0c5b08c7cc8f7494d7a12e7001f)](https://api.securityscorecards.dev/projects/github.com/nodejs/nodejs.org/?commit=1fbd908497ece0c5b08c7cc8f7494d7a12e7001f)

In the Request2 the payload does not include all the checks, for example `"CI-Tests"` is missing inside [the checks](https://api.securityscorecards.dev/#/results/getResult). 

**Reproduction steps**
1. You can check this in action at: https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/nodejs/nodejs.org/compare/1fbd908497ece0c5b08c7cc8f7494d7a12e7001f/bd31d489615b424202553ffe1a5093a19d5e5e1f (explore the network request in the chrome dev tools) or do the HTTP request directly in the browser and compare the payloads

**Expected behavior**

I will expect both payloads to include all the checks included in the scorecard, or at least an error code that explains this behaviour, so the API consumers can control the error.

**Additional context**

This bug is affecting:
- [openssf-scorecard-api-visualizer](https://github.com/KoolTheba/openssf-scorecard-api-visualizer) cc: @kooltheba
- [OpenSSF Scorecard Monitor](https://github.com/marketplace/actions/openssf-scorecard-monitor)

**Comment by spencerschrock** [comment]
I believe this is a matter of where the result is sourced. The API pulls from the GitHub action published results if available, or the weekly cron if not.
https://github.com/ossf/scorecard-webapp/blob/e7be60069b18df32c7d3b003dd9daca6a622e6c5/app/server/get_results.go#L70-L88

```diff
diff checks1 checks2
4d3
< "CI-Tests"
6d4
< "Contributors"
8d5
< "Dependency-Update-Tool"
```

These are the checks disabled in the weekly cron:
https://github.com/ossf/scorecard/blob/b68ef18c9691a7be16dbbc60c32cd736dd372d1d/cron/config/config.yaml#L48

The output is basically tied to the checks requested, so
```
scorecard --repo foo/bar --checks Vulnerabilities
```
will only have the Vulnerabilities check in its result. Which is why those 3 are missing.

Your second request comes from before the action was installed, so there's no other data to grab.

I believe this is working as intended.

**Comment by UlisesGascon** [comment]
Thanks @spencerschrock this makes sense! Thanks for the complete response 👍
