### ISSUE TITLE
Feature: Revisit number of license probes

### ISSUE THREAD

**Issue by AdamKorcz** [ossf/scorecard#3590]
The license probes could potentially be reduced from 3 to 2 as suggested in https://github.com/ossf/scorecard/pull/3465#discussion_r1361279509

**Comment by spencerschrock** [comment]
@laurentsimon I'm thinking of removing the `hasLicenseFileAtTopDir` probe entirely. and making `hasLicenseFile` worth 9 instead of 6. Thoughts?

When the new scoring was introduced in #2442, 3 points were awarded for finding licenses in expected locations vs "other".

https://github.com/ossf/scorecard/blob/28b116f1a79f548b3b3bd595d8e379d0b7cadeaf/checks/evaluation/license.go#L37-L50

but 1.5 years later nothing ever sets `LicenseAttributionTypeOther`, only API and heuristics based detection.

**Comment by laurentsimon** [comment]
> @laurentsimon I'm thinking of removing the `hasLicenseFileAtTopDir` probe entirely. and making `hasLicenseFile` worth 9 instead of 6. Thoughts? Draft is at #3955
> 
> When the new scoring was introduced in #2442, 3 points were awarded for finding licenses in expected locations vs "other".
> 
> https://github.com/ossf/scorecard/blob/28b116f1a79f548b3b3bd595d8e379d0b7cadeaf/checks/evaluation/license.go#L37-L50
> 
> but 1.5 years later nothing ever sets `LicenseAttributionTypeOther`, only API and heuristics based detection.

@shissam can you chime in?

**Comment by shissam** [comment]
In the original change - ```LicenseAttributionTypeOther``` was a bit of a placeholder for "the old way scorecard" (at the time) probed for licenses which was on the way out. At that same time, ```LicenseAttributionTypeOther``` (now looking back in time) this case was unreachable (and I cannot recall why that could have been--could have been for my original regression testing). As I understand (now) and with the removal of ```hasLicenseFileAtTopDir```, this case will (again) be unreachable--so from that perspective, I agree.

The greatest reason I asked for the PR back in the day, was a matter of _confidence_. This change does not effect that. I suppose we could discuss whether ```LicenseAttributionTypeAPI``` and ```LicenseAttributionTypeHeuristics``` warrant  the same level of _confidence_ (that being ```...API``` is higher--and perhaps a higher score over ```...Heuristics```), however as far as this PR goes, making ```hasLicenseFile``` ```9``` rather than ```6``` maintains the License check _contract_ in checks documentation. I would state, however, that back when I was conducting the analysis for this original change, the _old_ probe was too easily tripped up by both false positives and false negatives with license detection and having the current ```...Heuristics``` stick to well defined locations for detecting the license file should still be necessary--I don't believe this PR changes that.
