### ISSUE TITLE
improve binary artifact and license tests to match other checks

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#4032]
Both Binary-Artifacts and License checks have TODOs about using a gomock repoclient.

https://github.com/ossf/scorecard/blob/0b9dfb656f1796c7c693ad74f5193657b6a81e0b/checks/binary_artifact_test.go#L63-L65

https://github.com/ossf/scorecard/blob/0b9dfb656f1796c7c693ad74f5193657b6a81e0b/checks/license_test.go#L71-L73

Additionally `Binary-Artifacts` has is a very basic test which just check the score and not other aspects of the `CheckResult` (like logging).
https://github.com/ossf/scorecard/blob/0b9dfb656f1796c7c693ad74f5193657b6a81e0b/checks/binary_artifact_test.go#L86-L89

It'd be nice to get both of these cleaned up like some of the other checks to:
1. Use gomock
2. use `scut.ValidateTestReturn`

For example like `dangerous_workflow_test.go`
https://github.com/ossf/scorecard/blob/0b9dfb656f1796c7c693ad74f5193657b6a81e0b/checks/dangerous_workflow_test.go#L80-L95

**Comment by seelder** [comment]
I think maybe I can work on this one? I haven't used gomock before, but it looks like BinaryArtifacts uses a lot of the same functions as DangerousWorkflow so hopefully I can figure it out.

**Comment by spencerschrock** [comment]
DangerousWorkflow should be a good template, but happy to answer any questions as needed

**Comment by seelder** [comment]
(@spencerschrock) - currently the [ListLicenses function for  the localDirRepo client](https://github.com/ossf/scorecard/blob/main/clients/localdir/client.go#L259) throws an Unsupported Feature error, which is then [handled by the raw license check](https://github.com/ossf/scorecard/blob/main/checks/raw/license.go#L154). Options I see include

1. create a mock that just throws an UnsupportedFeature error, similar to the existing functionality (I already have a working version of this, I think)

2. create a mock that actually returns something from ListLicenses, however, that would replicate a lot of the existing functionality for handling these cases in the check itself

3. Testing both 1 and 2 using different test cases with different mocks (adding a couple test cases to do so), although it seems like the difference in functionality should be tested in the raw/checks/license_test rather than here, so this might involve some other test design decisions

**_My questions are along the lines of - Is the functionality in the license check that handles an unsupportedFeature for listLicenses intended to be permanent? Are any of the options above preferable given the test designs for the project?_**


I am probably over-thinking this. If so and if option 1 is fine, I can go ahead and submit a PR.

Thanks!

**Comment by spencerschrock** [comment]
Option (1) sounds reasonable and a more direct translation of the existing tests, and would be a good first PR. 

Depending on how much you want to do, creating a separate test which uses `ListLicenses` (effectively option 3) also sounds good.
