### ISSUE TITLE
BUG: Missing data for repository

### ISSUE THREAD

**Issue by nitrocode** [ossf/scorecard#4329]
**Describe the bug**
I noticed some projects have data like this

https://securityscorecards.dev/viewer/?uri=github.com/runatlantis/atlantis
https://securityscorecards.dev/viewer/?uri=github.com/renovatebot/renovate

And some do not like this

https://securityscorecards.dev/viewer/?uri=github.com%2Fcloudposse%2Fterraform-aws-ecr
https://securityscorecards.dev/viewer/?uri=github.com%2Fcloudposse%2Fatmos

> The Scorecard report requested was not found

How come? How can I add the missing data? I ran the `scorecard` app locally and it didn't make a difference in the UI.

**Reproduction steps**
1. See the above broken links

**Expected behavior**
Expected to see scorecard results of repo

**Additional context**
N/A

**Comment by lelia** [comment]
Hi @nitrocode, at a glance it looks like these two `cloudposse` projects may not be publishing Scorecard results. Are you a maintainer for these projects? If so, the [Scorecard Action](https://github.com/ossf/scorecard-action?tab=readme-ov-file#workflow-setup-required) is your best bet for getting started. Of course, you are welcome to run the Scorecard CLI locally, but this isn't as scalable a solution, and you'll need to make sure the `publish_results` flag is set to `true` in either case, otherwise the results will not appear on https://securityscorecards.dev

While I was unable to find a Scorecard workflow file for `runatlantis/atlantis` (`renovatebot/renovate` hosts theirs [here](https://github.com/renovatebot/renovate/blob/main/.github/workflows/scorecard.yml)), it looks like both `atlantis` and `renovate` have their Scorecard results automatically [published via weekly cron](https://github.com/ossf/scorecard?tab=readme-ov-file#public-data) (see full list of entries in `./cron/internal/data/projects.csv`). Since these two projects (plus several other `cloudposse` projects, interestingly) are part of the weekly cron, their results will always be published, even if nobody is running Scorecard for these projects locally or using the Scorecard Action.

**Comment by nitrocode** [comment]
Thank you. I was searching for the above error on projects without data and should have just read the readme 😅
