### ISSUE TITLE
New check: Do contributors and maintainers have 2fa enabled?

### ISSUE THREAD

**Issue by kimsterv** [ossf/scorecard#7]
Do all contributors have 2 factor authentication enabled on their accounts?

**Comment by naveensrinivasan** [comment]
I think the more practical would be "Do top 5/10contributors have 2FA enabled"?

**Comment by laurentsimon** [comment]
> I think the more practical would be "Do top 5/10contributors have 2FA enabled"?

probably depends on how many contributors the project has?
We could also check that reviewers have 2FA. A compromised contributor may try to push bad code but would be detected by reviewers. Having a score instead of a binary pass/fail check would also help in general. It would encourage developers to make incremental improvements towards a long-term goal.

**Comment by laurentsimon** [comment]
API for org https://docs.github.com/en/rest/reference/orgs#members. May require special permission to use.

**Comment by chrismcgehee** [comment]
> API for org https://docs.github.com/en/rest/reference/orgs#members. May require special permission to use.

This API allows querying for users in your organization that do not have 2FA enabled. It wouldn't fit our needs of being able to tell if an arbitrary user has 2FA enabled. I would be surprised if Github ever published an API allowing querying whether arbitrary users have 2FA enabled. I think a lot of people wouldn't be comfortable with it being public knowledge that they don't use 2FA. We might not ever be able to do this issue.

**Comment by laurentsimon** [comment]
if we could query the list of maintainers for a repo/org, we could then cross-check which users don't have 2FA enabled. I've not looked closely at the API, though

**Comment by laurentsimon** [comment]
ok, yes allstar works well too. Im adding them as scorecard issues first and allstar is the fallback solution in my mind, since allstar is for orgs but scorecard can be more broadly used. Here's another one that I would like to have in scorecard, but may only be viable for allstar https://github.com/ossf/scorecard/issues/1655

**Comment by david-a-wheeler** [comment]
> It looks like this API is only available if you are the owner of that organization, so I don't think it would be useful in Scorecard.

We already have another (experimental) measure in Scorecard that requires this. So I think it *is* appropriate to add it, and only measure it when it's possible. Also, Scorecard isn't limited to GitHub; we're adding GitLab, and more may follow (I hope). Just include some sort of marker indicating in a machine-processable way that "we could not get this data" in those cases.

**Comment by afmarcum** [comment]
GitHub is requiring MFA for all contributors by the end of 2023 and project documentation states limitations in creating this check with a strong recommendation for using MFA generally so this issue can probably be closed.

If there is no feedback in the next 7 days to the contrary, then this issue will be closed.

**Comment by david-a-wheeler** [comment]
[afmarcum](https://github.com/afmarcum) : I don't think it's required for GitLab though.
