### ISSUE TITLE
Cant check pypi package

### ISSUE THREAD

**Issue by neonlyis** [ossf/scorecard#715]
Hello, I am trying to check score of a pypi package babel but I think i might not be using it correctly.
What am I doing wrong? can i specify a specific version of the package?
Thanks

[root@dockermachine ~]# docker run -e GITHUB_AUTH_TOKEN=token gcr.io/openssf/scorecard:latest --show-details --pypi=Babel
2021/07/20 10:41:43 could not find source repo for pypi package: Babel

**Comment by azeemshaikh38** [comment]
This is an interesting one. The reason this is happening is because https://pypi.org/pypi/Babel/json does not specify the Github URL for Babel. Wonder how effectively we can rely on https://pypi.org/pypi/<package_name> to give us information on a package. @naveensrinivasan 

For now, you can workaround this by running: 

```
docker run -e GITHUB_AUTH_TOKEN=<token> gcr.io/openssf/scorecard:latest --show-details --repo=https://github.com/python-babel/babel
```

Does this help @neonlyis ?

**Comment by azeemshaikh38** [comment]
Closing this. Re-open if needed.
