### ISSUE TITLE
BUG -  Git Tag Scorecard API upgrade

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#754]
**Describe the bug**
The scorecard was upgraded in this PR https://github.com/ossf/scorecard/pull/716 , but cannot fetch the until there is a corresponding git tag. https://blog.golang.org/publishing-go-modules
```
go get github.com/ossf/scorecard/v2
go: downloading github.com/ossf/scorecard v1.2.0
go get: module github.com/ossf/scorecard@upgrade found (v1.2.0), but does not contain package github.com/ossf/scorecard/v2
```

**Comment by naveensrinivasan** [comment]
cc @jeffmendoza

**Comment by jeffmendoza** [comment]
Yeah, for `go get` to work, the git tag (v2.x.x) needs to match the major version in go.mod. If you just `go get github.com/ossf/scorecard` now you get v1.2.0, because that is the last v1 version. v2.0.0 is essentially broken. There needs to be a new release with v.2.x.x tag and now the v2 in the go.mod for `go get github.com/ossf/scorecard/v2` to work.

**Comment by naveensrinivasan** [comment]
Planning to do that after today's meeting.

**Comment by naveensrinivasan** [comment]
@inferno-chromium @azeemshaikh38  Can we git tag `v2.1.0`?

**Comment by inferno-chromium** [comment]
> @inferno-chromium @azeemshaikh38 Can we git tag `v2.1.0`?

Sure, go ahead.

**Comment by naveensrinivasan** [comment]
Tagged with `v2.1.0` 

I was able to pull `go get github.com/ossf/scorecard/v2`

**Comment by naveensrinivasan** [comment]
@jeffmendoza  FYI.There is a breaking API Change `githubrepo.CreateGithubRepoClient`
