### ISSUE TITLE
Binary Artifacts: tar gz ?

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/scorecard#759]
Should we add tar and gz to the binary artifacts check?

ref: https://github.com/ossf/scorecard/blob/main/checks/binary_artifact.go#L50

**Comment by loosebazooka** [comment]
Is there a reason we care what kind of binary it is? Could it just be text (or ascii or whatever) vs non-text

**Comment by azeemshaikh38** [comment]
> Is there a reason we care what kind of binary it is? Could it just be text (or ascii or whatever) vs non-text

`BinaryArtifacts` specifically looks for executables since that represents a potential threat vector like remote code execution. Files like JPG etc., which are non-ASCII, can be present in a repository and we shouldn't flag that IMO. 

> Should we add tar and gz to the binary artifacts check?

I think this would trigger lot of false positives. Is having tar/gz files in a repo enough of a threat to warrant the false positives?

**Comment by jeffmendoza** [comment]
> I think this would trigger lot of false positives. Is having tar/gz files in a repo enough of a threat to warrant the false positives?

cc: @dlorenc 

Maybe a good candidate for the score based result, only having tar/gz could be a 6 or something. =)

**Comment by inferno-chromium** [comment]
> > I think this would trigger lot of false positives. Is having tar/gz files in a repo enough of a threat to warrant the false positives?
> 
> cc: @dlorenc
> 
> Maybe a good candidate for the score based result, only having tar/gz could be a 6 or something. =)

can you try running this on a few important repos, we would like to minimize false positives.

**Comment by dlorenc** [comment]
IMO it's more about whether something can be accurately reviewed by a human or not. A tar can't be reviewed without downloading it (and might even contain binaries!). Same for the gz representation.

**Comment by loosebazooka** [comment]
I imagine binary-artifacts is the kind of check that would have a lot of exceptions though.
for example, jib which build java containers tests against many (~100) jar and tars, not sure we would want that test infrastructure to be building those (and could they even build what we want reproducibly?)

**Comment by dlorenc** [comment]
Yep, something used only in tests seems like a valid exception.

**Comment by laurentsimon** [comment]
I have plans to also flag curl downloads that download zip, tar, etc because there are many cases where users download entire Linux trees within their Dockerfile.
I think it's fine to make the check more granular and remove some points from the score when zip, tar are in the repo. Of course, to be more accurate, we could try to unzip/untar recursively and see if there are binaries inside. We with, we'd have to be careful with DoS (large, recursive zip files) and directory traversal (if we unpack to disk)
