### ISSUE TITLE
BUG: Parsing errors

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#839]
Noticing many parsing errors during cron job. Not blocking cron job, but good to fix since otherwise we just return `ErrScorecardInternal`. Some examples to reproduce shown below:

```
scorecard --repo=github.com/ufal/udpipe --checks=Pinned-Dependencies

scorecard --repo=github.com/ubisoft/Sharpmake --checks=Pinned-Dependencies

scorecard --repo=github.com/uber/okbuck --checks=Pinned-Dependencies

scorecard --repo=github.com/uber/NullAway --checks=Pinned-Dependencies

scorecard --repo=github.com/aliyun/aliyun-odps-python-sdk --checks=Token-Permissions,Pinned-Dependencies

scorecard --repo=github.com/alibaba/GraphScope --checks=Token-Permissions

scorecard --repo=github.com/u-boot/u-boot --checks=Pinned-Dependencies
``` 

There might be more cases. Will add as I find them. Would be good to fix these and add these repos to `cron/data/projects.release.csv` as and when we fix them.

**Comment by laurentsimon** [comment]
@chrismcgehee are you interested in helping for this issue? It's in the Pinned-Dependency check that you're looking at to add lines.

**Comment by chrismcgehee** [comment]
Sure, I'll take this one.

**Comment by chrismcgehee** [comment]
There are several different categories these parsing errors fall into. I'll list them and state how I plan to address them:
- Treating powershell code as shell code
          Example: [ubisoft/Sharpmake](https://github.com/ubisoft/Sharpmake/blob/62f11eb03f5730dc2e02d250ad275b9b77cc2815/.github/workflows/actions.yml#L115)
          How to fix: Check for `if: runner.os == 'Windows'`. Skip for now and add a todo to parse powershell code
- Valid bash that is not parsed correctly
          Example: [uber/NullAway](https://github.com/uber/NullAway/blob/master/config/hooks/pre-commit#L7)
          How to fix: Open issue in mvdan.cc/sh/v3/syntax.
- Bash files in `.github/workflows`
          Example: [alibaba/GraphScope](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/hadoop_scripts/prepare_hadoop.sh)
          How to fix: Parse as shell code instead of yaml
- Non-shell files with ".sh" extension
          Example: [u-boot/u-boot](https://github.com/u-boot/u-boot/blob/master/scripts/ld-version.sh)
          How to fix: Evaluate if shebang is for a recognized shell program (/bin/bash, /bin/zsh, etc.) before trying to parse

Let me know if you have any suggestions.

**Comment by azeemshaikh38** [comment]
Thanks Chris, this is great! Comments inline:

> * Treating powershell code as shell code
>   Example: [ubisoft/Sharpmake](https://github.com/ubisoft/Sharpmake/blob/62f11eb03f5730dc2e02d250ad275b9b77cc2815/.github/workflows/actions.yml#L115)
>   How to fix: Check for `if: runner.os == 'Windows'`. Skip for now and add a todo to parse powershell code

How would we check for this? If we have parsers that can understand this, that can work. But if we are planning to use string matching to do this, I'm not too sure about this one. 

> * Valid bash that is not parsed correctly
>   Example: [uber/NullAway](https://github.com/uber/NullAway/blob/master/config/hooks/pre-commit#L7)
>   How to fix: Open issue in mvdan.cc/sh/v3/syntax.
> * Bash files in `.github/workflows`
>   Example: [alibaba/GraphScope](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/hadoop_scripts/prepare_hadoop.sh)
>   How to fix: Parse as shell code instead of yaml
> * Non-shell files with ".sh" extension
>   Example: [u-boot/u-boot](https://github.com/u-boot/u-boot/blob/master/scripts/ld-version.sh)
>   How to fix: Evaluate if shebang is for a recognized shell program (/bin/bash, /bin/zsh, etc.) before trying to parse

All of this sound good to me.

**Comment by chrismcgehee** [comment]
> How would we check for this? If we have parsers that can understand this, that can work. But if we are planning to use string matching to do this, I'm not too sure about this one.

This is a pretty simple check, so I think string matching would be appropriate here. I was unable to find any open-source parsers for github workflows.

**Comment by laurentsimon** [comment]
> Thanks Chris, this is great! Comments inline:
> 
> > * Treating powershell code as shell code
> >   Example: [ubisoft/Sharpmake](https://github.com/ubisoft/Sharpmake/blob/62f11eb03f5730dc2e02d250ad275b9b77cc2815/.github/workflows/actions.yml#L115)
> >   How to fix: Check for `if: runner.os == 'Windows'`. Skip for now and add a todo to parse powershell code

workflows also have a `os` param you can additionally look for.

> 
> How would we check for this? If we have parsers that can understand this, that can work. But if we are planning to use string matching to do this, I'm not too sure about this one.
> 
> > * Valid bash that is not parsed correctly
> >   Example: [uber/NullAway](https://github.com/uber/NullAway/blob/master/config/hooks/pre-commit#L7)
> >   How to fix: Open issue in mvdan.cc/sh/v3/syntax.
> > * Bash files in `.github/workflows`
> >   Example: [alibaba/GraphScope](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/hadoop_scripts/prepare_hadoop.sh)
> >   How to fix: Parse as shell code instead of yaml

you should not need to parse the file if it's a shell, because it will be done by `validateShellScriptIsFreeOfInsecureDownloads `. All you need to do is return early.
We're already calling `isShellScriptFile()` (see https://github.com/ossf/scorecard/blob/main/checks/pinned_dependencies.go#L419) to check if a file is a shell script, and I forgot to add it for github workflows :-) So I think just calling isShellScriptFile` should be enough.

> > * Non-shell files with ".sh" extension
> >   Example: [u-boot/u-boot](https://github.com/u-boot/u-boot/blob/master/scripts/ld-version.sh)
> >   How to fix: Evaluate if shebang is for a recognized shell program (/bin/bash, /bin/zsh, etc.) before trying to parse

this is already done in `isSupportedShell()`, see supported shell names in https://github.com/ossf/scorecard/blob/main/checks/shell_download_validate.go#L35
I think https://github.com/ossf/scorecard/blob/main/checks/pinned_dependencies.go#L193 is missing a call to `isSupportedShell()`

> 
> All of this sound good to me.

**Comment by chrismcgehee** [comment]
Laurent, thanks for the comments.
> workflows also have a `os` param you can additionally look for.

Is there an example yml file you can point to that shows the `os` param?

**Comment by laurentsimon** [comment]
a few places:
- https://github.com/ubisoft/Sharpmake/blob/62f11eb03f5730dc2e02d250ad275b9b77cc2815/.github/workflows/actions.yml#L94
(documented in https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-running-with-multiple-operating-systems)
- `runs-on` attribute: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on (can be an array or a string I think)

**Comment by chrismcgehee** [comment]
Ok, maybe if all the values in `runs-on` or `strategy.matrix.os` start with "windows-", we can assume the script is powershell. Otherwise, we can look for `if: runner.os == 'Windows'` (using a slightly more sophisticated regex).

**Comment by laurentsimon** [comment]
sounds like a reasonable approach. Also verify that if `if: runner.os == 'Windows'` is present, at least one windows os is specified in `runs-on`

**Comment by azeemshaikh38** [comment]
One more from #954 

```
scorecard --repo=github.com/sourcegraph/sourcegraph --checks Pinned-Dependencies 
```

**Comment by chrismcgehee** [comment]
The error from https://github.com/crawl/crawl is because there is a [python file](https://github.com/crawl/crawl/blob/69098e2f6d3e6417edc2f7741f8c987ef8140948/.github/workflows/deps.py) in `.github/workflows`. I'll fix this by only trying to unmarshal files in `.github/workflows` if it has a `.yml` or `.yaml` extension. From https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions:
> Workflow files use YAML syntax, and must have either a .yml or .yaml file extension.

The error from https://github.com/sourcegraph/sourcegraph is actually failing on the [CODENOTIFY](https://github.com/sourcegraph/sourcegraph/blob/a628631cfda2cca5817ffdca9e9d084fd37a75dd/.github/workflows/CODENOTIFY) file. The same fix should handle this one also. @nathan-415, fyi.

**Comment by naveensrinivasan** [comment]
@chrismcgehee  Can we close this?

**Comment by chrismcgehee** [comment]
> @chrismcgehee  Can we close this?

Not yet. There's still one more issue I need to address: shell code that isn't able to be parsed.

**Comment by laurentsimon** [comment]
I found another one `--repo=tensorflow/tensorflow` that fails `invalid shell code: 18:48: &> must be followed by a word`

**Comment by chrismcgehee** [comment]
Ok, there are 4 repos that give us `invalid shell code`. Here's the deal with each of them:
- [ufal/udpipe](https://github.com/ufal/udpipe/blob/e51f02d2744cdfd4a29efc1320644ea04d535f0b/releases/pypi/README.sh#42) - If you run `bash -n` on this file, it gives a warning due to the unclosed heredoc. I don't expect mvdan/sh to parse bash code that gives warnings.
- [uber/okbuck](https://github.com/uber/okbuck/blob/886c45bc315bd1fb5c81ff282fcdc0beed0c76ea/buckw#L100) - This is valid bash syntax, so I've opened https://github.com/mvdan/sh/issues/729.
- [uber/NullAway](https://github.com/uber/NullAway/blob/master/config/hooks/pre-commit#L7) - This also is valid bash, but mvdan/sh [states](https://github.com/mvdan/sh/blob/master/README.md) that `$((` and `((` ambiguity is not supported. I think we should skip attempting to parse this file.
- [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/tests/reducer/unsupported-op-test.sh#L18) - This is actually invalid bash syntax. I think we should skip parsing files with invalid bash.

That leads me to a broader question of how we handle shell code that we are unable to parse. Currently, the entire check fails with a score of '?'. What I would like to do instead is log a warning whenever we fail to parse a file, but continue on with the check. It would be good if we put a system in place to monitor for these warnings so we can evaluate if there is a bug in our parsing code. How does this sound?

**Comment by azeemshaikh38** [comment]
> It would be good if we put a system in place to monitor for these warnings

+1. See https://github.com/ossf/scorecard/blob/main/stats/views.go#L50. You can use that to record/monitor these parse errors. 

We can start with this to get a sense of how bad the problem is and then decide on whether we should log a warning and continue.

**Comment by azeemshaikh38** [comment]
@chrismcgehee thanks for fixing so many of the parsing issues. The number of parsing errors we see in the cron job has significantly reduced!

Some new parsing issues I see as of now: 

```
./scorecard --repo=github.com/ljharb/array-includes

./scorecard --repo=github.com/llooker/swilt_test1

./scorecard --repo=github.com/llvm/llvm-project

./scorecard --repo=github.com/logur/logur

./scorecard --repo=github.com/looker/ci_demo

./scorecard --repo=github.com/lucas-clemente/quic-go
```

**Comment by azeemshaikh38** [comment]
Update on the monitoring @chrismcgehee put in place for shell errors -

**Comment by chrismcgehee** [comment]
@azeemshaikh38 Thanks for fixing the panicky code.
@naveensrinivasan That library looks great! Glad you found it. I would love doing less maintenance for parsing actions.
@asraa I expect that when we move to the library for parsing actions, the yaml included in the blog will get parsed correctly. If it doesn't, we can look into it further at that time.

**Comment by naveensrinivasan** [comment]
> @azeemshaikh38 Thanks for fixing the panicky code.
> @naveensrinivasan That library looks great! Glad you found it. I would love doing less maintenance for parsing actions.
> @asraa I expect that when we move to the library for parsing actions, the yaml included in the blog will get parsed correctly. If it doesn't, we can look into it further at that time.


@chrismcgehee Do you want to do this? Or I can take it.

**Comment by chrismcgehee** [comment]
> @chrismcgehee Do you want to do this? Or I can take it.

I can do this one.

**Comment by naveensrinivasan** [comment]
> > @chrismcgehee Do you want to do this? Or I can take it.
> 
> I can do this one.

Thanks

**Comment by azeemshaikh38** [comment]
Parsing errors that showed up with the new actionlint parser:

```
./scorecard --repo=github.com/containous/maesh --checks=Pinned-Dependencies
./scorecard --repo=github.com/mahmoud/boltons --checks=Pinned-Dependencies
```

**Comment by spencerschrock** [comment]
Closing as most of the parse errors here were fixed, and the fact that we continue on error now (#3515). More recent parse errors have their own issues: e.g. #3075
