### ISSUE TITLE
Feature: add line number to Token-Permissions detail reporting

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#886]
see the title. It's identical to https://github.com/ossf/scorecard/issues/725 but for `Token-Permissions` check.

**Comment by laurentsimon** [comment]
FYI @chrismcgehee

**Comment by laurentsimon** [comment]
@chrismcgehee I think you're working on it, right? Assigning to you. If you're not, please un-assign.

**Comment by laurentsimon** [comment]
Does https://github.com/ossf/scorecard/pull/1363 close this issue?

**Comment by chrismcgehee** [comment]
> Does #1363 close this issue?

It does not. These functions (and the functions they call) still need the line number to be set correctly:
- [createIgnoredPermissions](https://github.com/ossf/scorecard/blob/86fd966dc41886edec168e071ee11227ea262c71/checks/permissions.go#L400)
- [isSARIFUploadWorkflow](https://github.com/ossf/scorecard/blob/86fd966dc41886edec168e071ee11227ea262c71/checks/permissions.go#L416)
- 
The fix here will be more involved because we'll have to go several steps up in the call stack to pass in a structured object instead of a string.
